libraries:
  Movies_yes_radarr:
    library_name: Movies
    collection_files:
    - file: config/Movies_yes_radarr.yml
    radarr:
      url: http://192.168.1.111:7878
      token: <<radarr-token>>
      quality_profile: Not Remux
      root_folder_path: /mnt/unionfs/Media/Movies
      availability: released
      add_existing: false
      upgrade_existing: false
      ignore_cache: false
      monitor_existing: false
      add_missing: true
      monitor: true
      search: true
    webhooks:
      changes: notifiarr
  Movies_no_radarr:
    library_name: Movies
    operations:
      assets_for_all: true
    collection_files:
    - file: config/Movies.yml
    - file: config/Genres.yml
    - default: seasonal
      sort_title: +00_<<key_name>> Movies
      template_variables:
        name_format: <<key_name>> Movies
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - default: resolution
      template_variables:
        horizontal_align: center
        vertical_align: top
        use_resolution: false
        horizontal_offset: 0
        vertical_offset: 10
        back_color: '#0000'
        back_height: 100
  Movies-4KHDR-dv:
    library_name: Movies-4KHDR-dv
    operations:
      assets_for_all: true
    radarr:
      url: http://192.168.1.111:7879
      token: <<radarr4k-token>>
      quality_profile: Remux => Bluray (HQ)
      root_folder_path: /mnt/unionfs/Media/Movies-4K-dv
      availability: released
      add_missing: false
      add_existing: false
      upgrade_existing: false
      ignore_cache: false
      monitor: true
      search: false
      monitor_existing: false
    collection_files:
    - file: config/Movies.yml
    - file: config/Movies_reference_audio_collection.yml
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - file: /config/jmxd_github_overlay_images/media_info_no_editions.yml
      template_variables:
        use_edition: false
        use_resolution: false
        use_gradient_bottom: false
        use_gradient_top: true
        vertical_align: top
        horizontal_align: left
        vertical_offset: 10
        horizontal_offset: 10
        file_DV-HDR: config//jmxd_github_overlay_images/media_info/codec/DV-HDR_extended.png
        file_DV-Plus: config/jmxd_github_overlay_images/media_info/codec/DV-Plus_extended.png
    - file: /config/jmxd_github_overlay_images/media_info_edition_left-aligned.yml
      template_variables:
        edition_only: true
        use_gradient_bottom: false
        use_gradient_top: false
        vertical_align: top
        horizontal_align: left
        vertical_offset: 70
        horizontal_offset: 30
  test:
    library_name: pmm_test_library
    operations:
      assets_for_all: true
    remove_overlays: false
    # reapply_overlays: true
    overlay_files:
    - file: /config/jmxd_github_overlay_images/media_info_no_editions.yml
      template_variables:
        # video_only: true
        # use_combined: true
        use_edition: false
        use_resolution: false
        use_gradient_bottom: false
        use_gradient_top: true
        vertical_align: top
        horizontal_align: left
        vertical_offset: 10
        horizontal_offset: 10
        file_DV-HDR: config//jmxd_github_overlay_images/media_info/codec/DV-HDR_extended.png
        file_DV-Plus: config/jmxd_github_overlay_images/media_info/codec/DV-Plus_extended.png
    - file: /config/jmxd_github_overlay_images/media_info_edition_left-aligned.yml
      template_variables:
        edition_only: true
        use_gradient_bottom: false
        use_gradient_top: false
        vertical_align: top
        horizontal_align: left
        vertical_offset: 70
        # vertical_offset: 140
        horizontal_offset: 30
    # - file: /config/jmxd_github_overlay_images/media_info.yml
    #   template_variables:
    #     audio_only: true
    #     use_gradient_bottom: false
    #     use_gradient_top: false
    #     vertical_align: top
    #     horizontal_align: left
    #     # vertical_offset: 70
    #     vertical_offset: 70
    #     horizontal_offset: 10
  Movies-4KHDR:
    library_name: Movies-4KHDR
    operations:
      assets_for_all: true
    collection_files:
    - file: config/Movies.yml
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - file: /config/jmxd_github_overlay_images/media_info_no_editions.yml
      template_variables:
        use_edition: false
        use_resolution: false
        use_gradient_bottom: false
        use_gradient_top: true
        vertical_align: top
        horizontal_align: left
        vertical_offset: 10
        horizontal_offset: 10
        file_DV-HDR: config//jmxd_github_overlay_images/media_info/codec/DV-HDR_extended.png
        file_DV-Plus: config/jmxd_github_overlay_images/media_info/codec/DV-Plus_extended.png
    - file: /config/jmxd_github_overlay_images/media_info_edition_left-aligned.yml
      template_variables:
        edition_only: true
        use_gradient_bottom: false
        use_gradient_top: false
        vertical_align: top
        horizontal_align: left
        vertical_offset: 70
        horizontal_offset: 30
  TV Shows:
    operations:
      assets_for_all: true
    collection_files:
    - file: config/TV_Shows.yml
    - file: config/TV_Shows_Studios.yml
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - default: status
      template_variables:
        text_airing: A  I  R  I  N  G
        text_returning: R  E  T  U  R  N  I  N  G
        text_canceled: C  A  N  C  E  L  E  D
        text_ended: E  N  D  E  D
        horizontal_align: center
        vertical_offset: 45
        vertical_align: bottom
        font_color_airing: '#27C24C'
        font_color_returning: '#FFA500'
        font_color_canceled: '#ED1F1F'
        font_color_ended: '#FF0000'
        back_color: '#000000'
        back_width_airing: 300
        back_width_returning: 480
        back_width_canceled: 430
        back_width_ended: 280
        back_height: 34
        font: config/fonts/Arial.ttf
        font_size: 44
    - default: network
      template_variables:
        horizontal_align: center
        vertical_offset: 50
        vertical_align: top
        back_width: 621
        url: >-
          https://raw.githubusercontent.com/zarox-things/configs-and-stuff/main/plex-meta-manager/overlays/images/network/shadow/<<key>>.png
        back_color: '#00000000'
  TV 4K:
    library_name: TV Shows-4KHDR
    operations:
      assets_for_all: true
    settings:
      minimum_items: 1
    collection_files:
    - file: config/TV_Shows.yml
    - file: config/TV_Shows_Studios.yml
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - default: resolution
      template_variables:
        builder_level: show
        horizontal_align: left
        vertical_align: top
        horizontal_offset: 2
        vertical_offset: 50
        back_color: '#00000080'
        back_radius: 0
        back_align: left
        back_width: 250
        back_height: 70
        use_4k_dvhdr: false
        use_1080p_dvhdr: false
        use_dvhdr: false
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
    - default: audio_codec
      template_variables:
        builder_level: show
        horizontal_align: left
        vertical_align: top
        horizontal_offset: 2
        vertical_offset: 159
        back_color: '#00000080'
        back_radius: 0
        back_align: left
        back_width: 250
        back_height: 70
        use_truehd_atmos: false
        use_plus_atmos: false
        url_dolby_atmos: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/atmos.png
        url_dtsx: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/dtsx.png
        url_ma: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/ma.png
        use_truehd: false
        use_ma: false
        use_flac: false
        use_pcm: false
        use_hra: false
        use_plus: false
        use_dtses: false
        use_dts: false
        use_digital: false
        use_aac: false
        use_mp3: false
        use_opus: false
    - default: resolution
      template_variables:
        builder_level: episode
        horizontal_align: left
        vertical_align: top
        horizontal_offset: 2
        vertical_offset: 50
        back_color: '#00000080'
        back_radius: 0
        back_align: left
        back_width: 250
        back_height: 70
        use_4k_dvhdr: false
        use_1080p_dvhdr: false
        use_dvhdr: false
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
    - default: audio_codec
      template_variables:
        builder_level: episode
        horizontal_align: left
        vertical_align: top
        horizontal_offset: 2
        vertical_offset: 159
        back_color: '#00000080'
        back_radius: 0
        back_align: left
        back_width: 250
        back_height: 70
        use_truehd_atmos: false
        use_plus_atmos: false
        url_dolby_atmos: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/atmos.png
        url_dtsx: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/dtsx.png
        url_ma: >-
          https://raw.githubusercontent.com/Kometa-Team/Kometa/master/defaults/overlays/images/audio_codec/compact/ma.png
        use_truehd: false
        use_ma: false
        use_flac: false
        use_pcm: false
        use_hra: false
        use_plus: false
        use_dtses: false
        use_dts: false
        use_digital: false
        use_aac: false
        use_mp3: false
        use_opus: false
    - default: status
      template_variables:
        text_airing: A  I  R  I  N  G
        text_returning: R  E  T  U  R  N  I  N  G
        text_canceled: C  A  N  C  E  L  E  D
        text_ended: E  N  D  E  D
        horizontal_align: center
        vertical_offset: 45
        vertical_align: bottom
        font_color_airing: '#27C24C'
        font_color_returning: '#FFA500'
        font_color_canceled: '#ED1F1F'
        font_color_ended: '#FF0000'
        back_color: '#000000'
        back_width_airing: 300
        back_width_returning: 480
        back_width_canceled: 430
        back_width_ended: 280
        back_height: 34
        font: config/fonts/Arial.ttf
        font_size: 44
    - default: network
      template_variables:
        horizontal_align: center
        vertical_offset: 50
        vertical_align: top
        back_width: 621
        url: >-
          https://raw.githubusercontent.com/zarox-things/configs-and-stuff/main/plex-meta-manager/overlays/images/network/shadow/<<key>>.png
        back_color: '#00000000'
  Anime:
    schedule: weekly(sunday)
    collection_files:
    - default: myanimelist
      template_variables:
        url_poster: >-
          https://raw.githubusercontent.com/Drazzilb08/pmm-custom-repo-posters/master/anime/<<key>>.jpg
        use_separator: false
        use_airing: false
        use_favorited: false
        visible_library_popular: true
        visible_library_top: true
        visible_library_season: true
    - default: streaming
      template_variables:
        url_poster: >-
          https://raw.githubusercontent.com/Drazzilb08/pmm-custom-repo-posters/master/streaming/<<key>>.jpg
        collection_mode: hide
        use_separator: false
        use_all4: false
        use_now: false
        sort_by: random
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - remove_overlays: false
    - reapply_overlays: false
    - default: studio
      template_variables:
        horizontal_align: center
        vertical_offset: 50
        vertical_align: top
        back_width: 621
        url: >-
          https://raw.githubusercontent.com/zarox-things/configs-and-stuff/main/shadow_logos/studio/<<key>>.png
        back_color: '#00000000'
    - default: status
      template_variables:
        text_airing: A  I  R  I  N  G
        text_returning: R  E  T  U  R  N  I  N  G
        text_canceled: C  A  N  C  E  L  E  D
        text_ended: E  N  D  E  D
        horizontal_align: center
        vertical_offset: 45
        vertical_align: bottom
        font_color_airing: '#27C24C'
        font_color_returning: '#FFA500'
        font_color_canceled: '#ED1F1F'
        font_color_ended: '#FF0000'
        back_color: '#000000'
        back_width_airing: 300
        back_width_returning: 480
        back_width_canceled: 430
        back_width_ended: 280
        back_height: 34
        font: config/fonts/Arial.ttf
        font_size: 44
    - default: languages
      template_variables:
        builder_level: episode
        languages:
        - en
        - ja
        style: square
        back_color: '#00000080'
        position:
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 30
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 91
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 152
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 213
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 304
          vertical_align: top
    operations:
      assets_for_all: true
      delete_collections:
        less: 2
      mass_genre_update: tmdb
      mass_content_rating_update: mdb_commonsense
      mass_originally_available_update: tmdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: tmdb
      mass_imdb_parental_labels: mild
      split_duplicates: false
  Anime Movies:
    collection_files:
    - repo: anime/anime_collection
      template_variables:
        collection_mode: hide_items
        use_separator: false
    - default: streaming
      template_variables:
        url_poster: >-
          https://raw.githubusercontent.com/Drazzilb08/pmm-custom-repo-posters/master/streaming/<<key_encoded>>.jpg
        collection_mode: hide
        use_separator: false
        use_crunchyroll: false
        use_hayu: false
        use_max: false
        use_all4: false
        use_now: false
        visible_library_appletv: true
        visible_library_bet: true
        visible_library_disney: true
        visible_library_max: true
        visible_library_hulu: true
        visible_library_netflix: true
        visible_library_paramount: true
        visible_library_peacock: true
        visible_library_amazon: true
        visible_library_showtime: true
        sort_by: random
    - repo: studio
      template_variables:
        url_poster: >-
          https://raw.githubusercontent.com/Drazzilb08/pmm-custom-repo-posters/master/studio/<<key>>.jpg
        collection_mode: hide
        visible_library_studio_ghibli: true
        use_separator: false
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
    - default: languages
      template_variables:
        builder_level: episode
        languages:
        - en
        - ja
        style: square
        back_color: '#00000080'
        position:
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 30
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 91
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 152
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 213
          vertical_align: top
        - horizontal_offset: 30
          horizontal_align: left
          vertical_offset: 304
          vertical_align: top
operations:
  assets_for_all: true
  delete_collections:
    less: 2
  mass_genre_update: tmdb
  mass_content_rating_update: mdb_commonsense
#  mass_studio_update: tmdb
  mass_originally_available_update: tmdb
  mass_audience_rating_update: mdb_tomatoesaudience
  mass_critic_rating_update: mdb_metacritic
  mass_user_rating_update: tmdb
  mass_imdb_parental_labels: mild
  split_duplicates: false
playlist_files:
- file: config/TV_Shows_Playlists.yml
- file: config/Movies_reference_audio_playlist.yml
settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  - /kometa_assets/
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: false
  save_report: false
  run_again_delay: 2
  asset_folders: true
  missing_only_released: false
  create_asset_folders: false
  delete_below_minimum: true
  minimum_items: 3
  asset_depth: 0
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  show_missing_assets: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  verify_ssl: true
  prioritize_assets: true
  playlist_report: true
  custom_repo: https://github.com/Drazzilb08/pmm-custom-repo/tree/master/
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
plex:
  url: http://192.168.1.51:32400
  token: <<plex-token>>
  timeout: 720
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache: 1024
  verify_ssl:
sonarr:
  url: http://192.168.1.111:8989
  token: <<sonarr-token>>
  root_folder_path: /mnt/unionfs/Media/TV
  quality_profile: Trash-WebDL
  series_type: standard
  add_missing: false
  add_existing: false
  upgrade_existing: false
  ignore_cache: false
  monitor: all
  language_profile: English
  season_folder: true
  search: false
  cutoff_search: false
  monitor_existing: false
  tag:
  sonarr_path:
  plex_path:
tmdb:
  apikey: <<tmdb-apikey>>
  language: en
  cache_expiration: 60
  region:
trakt:
  client_id: <<trakt-client-id>>
  client_secret: <<trakt-client-secret>>
  authorization:
    access_token: <<trakt-access-token>>
    token_type: Bearer
    expires_in: 7889237
    refresh_token: <<trakt-refresh-token>>
    scope: public
    created_at: 1718269253
  pin:
mal:
  client_id: <<mal-client-id>>
  client_secret: <<mal-client-secret>>
  authorization:
    access_token: <<mal-access-token>>
    token_type: Bearer
    expires_in: 2591999
    refresh_token: <<mal-refresh-token>>
  localhost_url: <<mal-localhost-url>>
  cache_expiration: 60
mdblist:
  apikey: <<mdblist-apikey>>
  cache_expiration: 60
notifiarr:
  apikey: <<notifiarr-apikey>>
  webhooks:
  error: notifiarr
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  delete:
  changes:
